In [1]:
import numpy as np

In [33]:
x = np.array([[1,2,3],[5,6,7]])
y = np.array([[1,2,1],[5,5,6]])
z = np.array ([[8,7,8],[9,3,2],[9,8,3],[6,1,7]])
w = np.array ([[[8,7,8],[9,3,2]],[[8,7,8],[9,3,2]]])
arr = np.array([[[1, 2, 3], [4, 5, 6],[1,5,4]], [[1, 2, 3], [4, 5, 6],[6,7,4]]])
print(x+y)
print(x.ndim)
print(z.ndim)
print (w.ndim)
print (arr.ndim)
print(arr.shape)
print(x.sum())


[[ 2  4  4]
 [10 11 13]]
2
2
3
3
(2, 3, 3)
24


In [27]:
arr = np.array([[-1, 2, 0, 4,6], [4, -0.5, 6, 0,8], [2.6, 0, 7, 8,3], [3, -7, 4, 2.0,1]]) 

In [28]:
arr.shape

(4, 5)

In [29]:
arr[:2]

array([[-1. ,  2. ,  0. ,  4. ,  6. ],
       [ 4. , -0.5,  6. ,  0. ,  8. ]])

In [30]:
arr[:2, ::3]

array([[-1.,  4.],
       [ 4.,  0.]])

In [35]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(3, 4)

print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [49]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

e = arr.reshape(2, 3, 2)

print(e)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [51]:
arr = np.array([[[1, 2, 3], [4, 5, 6],[1,5,4]], [[1, 2, 3], [4, 5, 6],[6,7,4]]])
r = arr.reshape(3,6)
print (r)

[[1 2 3 4 5 6]
 [1 5 4 1 2 3]
 [4 5 6 6 7 4]]


In [47]:
arr = np.array([[-1, 2, 0, 4], [4, -0.5, 6, 0], [2.6, 0, 7, 8], [3, -7, 4, 2.0]])
p = arr.reshape(2,8)
print (p)

[[-1.   2.   0.   4.   4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8.   3.  -7.   4.   2. ]]


In [54]:
arr = np.array([[[1, 2, 3], [4, 5, 6],[1,5,4]], [[1, 2, 3], [4, 5, 6],[6,7,4]]])
u = arr.reshape(18)
print (u)

[1 2 3 4 5 6 1 5 4 1 2 3 4 5 6 6 7 4]


In [56]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [57]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6
